### ISSUE TITLE
Game not launching

### ISSUE THREAD

**Issue by LeKripiY** [4EEZE/Create-Evil-Awake#1]
Hello, I wanted to try your modpack but it appears that the game is stuck on a white screen on launch, and when i try cliking it goes "not responding".
![image](https://github.com/4EEZE/Create-Evil-Awake/assets/77859121/9255d48b-1371-48fe-83f4-9ea36edaa8bc)
I think there is a mod that is too power hungry because it's not that big of a modpack (168 mods if I'm not mistaking) and I can't launch it.

**Comment by 4EEZE** [comment]
Hi, judging from the screenshot, the download has hung at the FancyMenu loading stage. Try disabling the " loadmyresources_forge_1.0.4_MC_1.19-1.19.2.jar " mod. It can heavily load the system at the first runs.

**Comment by 4EEZE** [comment]
If it doesn't work, then upload here the latest logs, your PC configuration. You can also just wait and don't click on anything, it usually works with heavy or medium modpacks.

**Comment by LeKripiY** [comment]
Hello again, I've tried launching the game with loadmyresources disabled, it didn't work, still tuck on loading, then i disabled fancymenu & the 2 others mods that goes with it (drippyloadingscreen & fancymenu audio), but still, the game is frozen on a white screen.
[latest.log](https://github.com/4EEZE/Create-Evil-Awake/files/13256274/latest.log)
also debug :
[debug.log](https://github.com/4EEZE/Create-Evil-Awake/files/13256275/debug.log)

My PC configuration :
CPU - AMD Ryzen 5 5600G
RAM - 32gb
GPU - Nvidia GeForce RTX 2060

**Comment by 4EEZE** [comment]
Strange, I got everything running fine, so it's not your PC, it doesn't look like a problem with the modpack either, the launcher also works fine.

Try to:
- Try to update your video card drivers;
- [Make minecraft a higher priority;](https://youtu.be/niNc4Xr46xk)
- Reinstall modpack;
- Try another launcher ( [PrismLauncher](https://prismlauncher.org/), [MultiMC ](https://multimc.org/)).

Hope this helps you.
