### ISSUE TITLE
Game keeps crashing, and more frequently

### ISSUE THREAD

**Issue by JustOsquo** [4EEZE/Create-Evil-Awake#3]
My game keeps crashing when running this pack, and its getting more and more frequent now to the point its unplayable (it wont run longer than ~5 minutes). These crashes happen suddenly, and without warning or prior lag/lagspikes. I have tried freeing up memory, as well as reinstalling the pack entirely, but neither has had any effect.
I have a game log from Modrinth of my most recent crash linked here:
https://mclo.gs/9t41601
I hope this issue can be resolved neatly. Thank you!

**Comment by JustOsquo** [comment]
Adding on to this, the game has apparently broken down entirely and i can no longer load my world (crashes instantly on loading, if i even make it to the point where i can load worlds without it crashing).
Not sure if it's related, but just in case I'm adding another log here:
https://mclo.gs/5JjVTlv

**Comment by JustOsquo** [comment]
(did not mean to close the issue)
Adding on to this, the game has broken down completely, and instantly crashes on loading my world, if it even makes it to that point before crashing.
Not sure if it's related, but just in case i have another log here:
https://mclo.gs/5JjVTlv

**Comment by 4EEZE** [comment]
I just installed modpack in Modrinth launcher and I had the same problem, minecraft just didn't have enough memory. You need to allocate more memory for it I recommend 6GB to 8GB.
I need to issue a warning about this so that situations like this don't happen again.
